### ISSUE TITLE
unable to extract ImageNet Weights

### ISSUE THREAD

**Issue by gargatik** [Cameltr/TransRef#10]
Hi, I want to use pretrained weights for imagenet but i am unable to extract them due to missing backbone module in provided pretrainied weights by you.

/mnt/train-data-4-hdd/gargatik/ood/triplet$ python tools/extract_backbone_weights.py ./ckpt/release_ep940.pth ./ckpt/release_smooth_ep940.pth
Traceback (most recent call last):
  File "tools/extract_backbone_weights.py", line 37, in <module>
    main()
  File "tools/extract_backbone_weights.py", line 32, in main
    raise Exception("Cannot find a backbone module in the checkpoint.")
Exception: Cannot find a backbone module in the checkpoint.

**Comment by Cameltr** [comment]
Hello, I did not pre-train the model on Imagenet, and there is also no `tools` folder in the code repository. Can you provide more detailed questions?

**Comment by gargatik** [comment]
Hi, sorry i posted question on wrong repository.

However, thanks for responding
