### ISSUE TITLE
image inpainting

### ISSUE THREAD

**Issue by Runing-Lab** [Cameltr/TransRef#2]
Hello, I am a new student, the training stage of image restoration I would like to ask, such as the paris dataset, is the scale mask and the dataset trained separately? Or 0%-60% masks and 14900 images together to train a model and then test the set with masks of each scale?

**Comment by Cameltr** [comment]
In the training stage, all the masks is required to participate in the training. During the test The proportion of masks (0–10%, 10–20%, ..., 50–
60%) is divided in order to illustrate the performance of the inpainting model in the face of different missing areas during the test

**Comment by Cameltr** [comment]
In the training stage, all the masks is required to participate in the training. During the test, the proportion of masks (0–10%, 10–20%, ..., 50– 60%) is divided in order to illustrate the performance of the inpainting model in the face of different missing areas.
