### ISSUE TITLE
Training images and test images

### ISSUE THREAD

**Issue by LYL-hub-source** [Cameltr/TransRef#3]
Hello, first of all, thank you for your contribution!
I would like to know that
1) Is the input during training the real image, the maske image and the reference image. Or is it the masked image, the mask image and the reference image
2) If the input is real image, mask image and reference image, can the real image and reference image be used in the same dataset
Looking forward to your reply

**Comment by Cameltr** [comment]
Hi！In the training stage, the inputs to the model are the real image，the mask image  and the reference image

**Comment by Cameltr** [comment]
Thanks for your question！
1. In the training stage, the inputs to the model are the real image( _I<sub>GT</sub>_ )，the mask image( _M_ ) and the reference image( _I<sub>ref </sub>_ ). Detail code can be found in [line981](https://github.com/Cameltr/TransRef/blob/main/models/TransRef.py) 
`def set_input(self, input_De, input_Mask, ref_De):`
2. First, in real life, it is difficult for people to obtain the original likeness of the damaged scene. Second, the acquired reference image and the damaged image are often temporally or spatially different, but similar in structure and texture details. Therefore, it is reasonable to use the reference image in the training stage for reference-guided inpainting task. If the input image and the reference image are the same ( self-reference? ), I think the trained result may be also good, you can also try it!

**Comment by LYL-hub-source** [comment]
Thank you for your reply. After training my own model and testing it, I found that:
1) When the same dataset is used for both the real image and the reference image, the restoration is almost perfect (extremely close to the real image, but the restoration results seem to be a bit blurred in pixels compared to the real image)
2) the lines 45 and 48 of the test code (test.py) represent the opposite meaning (I mean, should line 45 be filled with the path of the reference image; line 48 with the path of the real image)
