### ISSUE TITLE
Question regarding Element-wise Addition in Code Implementation

### ISSUE THREAD

**Issue by JaegukKim** [Cameltr/TransRef#5]
Thank you for the excellent paper and code. 
While reviewing the code implementation, I came across a question. 
In the paper, it's mentioned that the outputs, f-main (obtained through Main-PT) and f-ref (obtained through Ref-PT), are element-wise added to proceed to the next stage. However, I couldn't find this specific part in the code you provided. I'm curious about how the f-ref obtained from Ref-PA and Ref-PT is utilized in the next stage. Thank you.

**Comment by Cameltr** [comment]
Thank you for pointing out this issue. We have recently revised and redrawn the methodology flowchart in our latest submitted article, following the process in the code.
