### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by Vinayak-VG** [Cameltr/TransRef#8]
It's almost over a year now. Please update your code with the pretrained model and a testing code so that we could give our own testing images and it should inpaint accordingly

**Comment by Cameltr** [comment]
Thank you for your attention to our work! Unfortunately, this article has been rejected twice, which has delayed the timeline for making the model public as previously mentioned. I will upload it to Google Drive within this week and share the link. I apologize for any inconvenience this has caused you.

**Comment by ouenal** [comment]
Hi, thanks for the great work.

The weights on Google Drive seem to be corrupt and raise the following when trying to test the model:
RuntimeError: PytorchStreamReader failed reading zip archive: invalid header or archive is corrupted
Can you reupload the weights please.

**Comment by ouenal** [comment]
I think the issue is with the Google Drive upload and not the checkpoint itself. While I can't test the model properly as the link to download the masks do not work, I can at least load the checkpoint when I use the one downloaded from Baidu.

**Comment by Cameltr** [comment]
> I think the issue is with the Google Drive upload and not the checkpoint itself. While I can't test the model properly as the link to download the masks do not work, I can at least load the checkpoint when I use the one downloaded from Baidu.



> I think the issue is with the Google Drive upload and not the checkpoint itself. While I can't test the model properly as the link to download the masks do not work, I can at least load the checkpoint when I use the one downloaded from Baidu.

Perhaps there was an error during the upload process. I found that the model in Google Drive is about 2mb larger than the model on the server. So, I compressed the model in a `weights` folder and re-uploaded it to Google Cloud Drive, hoping it was the correct model

**Comment by ouenal** [comment]
Thanks for the quick update. Can you update the link on the README, I think it is still directing to the same file as before.

**Comment by ouenal** [comment]
Hi, the Google Drive checkpoint still fails to load giving the same error above. Furthermore, the keys in the Baidu link do not match with the model keys on Github. This is apparent when you remove the ```strict=False``` argument when loading the state dict.

**Comment by Vinayak-VG** [comment]
Yes, could you please link the correct google drive link for the newly updated working pretrained model. Thanks :)

**Comment by Cameltr** [comment]
> Yes, could you please link the correct Google Drive link for the newly updated working pretrained model. Thanks :)

Yes, I have corrected the Google Drive link. If you still have trouble, please get in touch with me.

**Comment by Vinayak-VG** [comment]
Hi, I used your newly linked model in Google Drive, but it doesn't seem to load the weights properly. As soon as I remove the strict=False and make it True, it shows a mismatch of keys while loading. Could you please check it once and make sure that either the model weights are correct or the model code is correct.

**Comment by Vinayak-VG** [comment]
<img width="1462" alt="Screenshot 2024-06-05 at 2 31 22 PM" src="https://github.com/Cameltr/TransRef/assets/80670240/cf3d03d4-0629-4f28-9682-fa0ce0e11333">

Due to which I get this bad result. The left-most is the reference image, the middle is the input, and the right-most image is the output. This is the result when I use strict=False. Could you please check it from your side

**Comment by ouenal** [comment]
The weights are still correct so you just need to convert the names from the old model they used into the new model from the repo. I wrote a script for it that you can find [here](https://drive.google.com/file/d/1XJUiZD2lL7k_UN8l6i-ieKJWu_LMEgU4/view?usp=sharing).

**Comment by Vinayak-VG** [comment]
Please provide access to the link you have provided above
